### ISSUE TITLE
Should we keep examples for each resource in the README?

### ISSUE THREAD

**Issue by hdiomede** [HewlettPackard/oneview-chef#15]
@jsmartt suggested and I totally agree that maybe we should keep only a few examples in the README and add links to the examples files.

**Comment by tmiotto** [comment]
Maybe we do not need to put detailed like it is right now. But, a little description would be interesting, mainly if there is some use case that is a bit different from the usual use case of the resources.

Regarding the README update, since it is a document that is not exactly directed to developers of this project itself, but for end-users, I think we just need to update it prior to releases, since the most use cases are available in the examples.

**Comment by jsmartt** [comment]
I think the README is actually the **first** thing any developer will look at when wanting to use this cookbook. I think we should document simple things there first, and point off to examples as a secondary resource for the complex, unusual, or special cases @tmiotto mentioned.

One advantage to this is that people skimming the cookbook can quickly see how it works, and some real code without having to navigate through an examples directory. Having no examples in the README might come off as either lazy or that this thing is really complicated, so we couldn't fit it all in this file.

Every time I use a new cookbook, the README is the first place I go, and it makes me very happy when I can get all the usage information right there in 1 spot. (The examples folder is an added bonus on top for complicated examples).

**Comment by tmiotto** [comment]
Yeah... I think it would be good to have all the basic info in one place too.

**Comment by tmiotto** [comment]
Created #19 to track the update to the previous resources without examples.

Also, I suggest to require the README update as a PR acceptance criteria, what do you guys think?

**Comment by hdiomede** [comment]
I totally agree with this :+1:

**Comment by jsmartt** [comment]
closing because #19 now exists to track this
