### ISSUE TITLE
Examples of server profile with configured local disk and added managed san

### ISSUE THREAD

**Issue by wingZero21** [HewlettPackard/oneview-chef#393]
### Scenario/Intent
[What you are trying to achieve but can't?]

Hi,

Are there any working examples of adding a local disk and managed existing san disk to the server profiles.

I can see the example here, however when attempting to add an attached volume I cant seem to find the option for enabling the managed san which is required, or where specifically this option needs to be put.

I can see its referenced in the API as "  "manageSanStorage" : true,", however using the chef I am unsure where this specific part needs adding.

Cheers

Details:
  "manageSanStorage" : true,

example - https://github.com/HewlettPackard/oneview-chef/blob/e0a0e3fa68c9dbfeecc9e004414225a9b43e807c/examples/server_profiles_with_volume_attachments_api500.rb

**Comment by wingZero21** [comment]
Any ideas on the manage san storage configuration option @jsmartt

**Comment by jsmartt** [comment]
Based on [how the Chef cookbook calls the SDK](https://github.com/HewlettPackard/oneview-chef/blob/v3.1.0/libraries/resource_providers/api200/server_profile_provider.rb#L38-#L42) and the [default functionality of the SDK](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/v5.6.0/lib/oneview-sdk/resource/api200/server_profile.rb#L204), I'm thinking that as long as you pass the volume name ([like this](https://github.com/HewlettPackard/oneview-chef/blob/e0a0e3fa68c9dbfeecc9e004414225a9b43e807c/examples/server_profiles_with_volume_attachments_api500.rb#L44)), it should set the `manageSanStorage` option to true.

You may also be able to use the data property in the resource to set it. For example:

```
oneview_server_profile_template 'ServerProfileTemplate1' do
  client my_client
  data(
    'sanStorage' => { 'manageSanStorage' => true }
  )
end
```

Let me know how it goes!

**Comment by wingZero21** [comment]
Hi,

I have added that example however I am getting back the below error.

Any ideas what might be causing this to occur @jsmartt 

Error
```
    NoMethodError
    -------------
    undefined method `each' for nil:NilClass

    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/resource_providers/api200/server_profile_provider.rb:50:in `block in build_volume_attachments'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/resource_providers/api200/server_profile_provider.rb:34:in `each'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/resource_providers/api200/server_profile_provider.rb:34:in `build_volume_attachments'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/resource_providers/api200/server_profile_template_provider.rb:27:in `load_with_properties'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/resource_providers/api200/server_profile_template_provider.rb:31:in `create_or_update'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/oneview_helper.rb:47:in `do_resource_action'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/resources/server_profile_template.rb:29:in `block in class_from_file'
```

Details:
```
      volume_attachments [{:volume=>"TEST_R1", :attachment_data=>{:id=>1, :lunType=>"Auto", :storagePaths=>[{:isEnabled=>true, :targetSelector=>"Auto", :connectionId=>1}]}}, {:volume_data=>{:name=>"TEST_R1", :description=>"TEST_R1", :size=>214748364800, :provisioningType=>"Thin", :isShareable=>******}, :storage_system=>"3par-01", :storage_pool=>"SSD_r1", :host_os_type=>"Windows Server 2016", :attachment_data=>{:id=>2, :lunType=>"Auto", :storagePaths=>[{:isEnabled=>true, :targetSelector=>"Auto", :connectionId=>1}]}}]
```

**Comment by jsmartt** [comment]
Hmm. From the stack trace, I can follow it to [here](https://github.com/HewlettPackard/oneview-chef/blob/v3.1.0/libraries/resource_providers/api200/server_profile_provider.rb#L50), but am not sure where in the SDK it's actually hitting the error; there are 2 each loops in [this method](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/v5.6.0/lib/oneview-sdk/resource/api200/server_profile.rb#L226). I'm guessing it's [this line](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/v5.6.0/lib/oneview-sdk/resource/api200/server_profile.rb#L236) though, since I don't think we're setting the `provisioningParameters` key anywhere.

Try setting `volume_attachements[<id>]['volume_data']['provisioningParameters']` to `{}`. For example:

```ruby
volume_attachments [
  {
    volume_data: {
      name: 'TEST_R1',
      description: 'TEST_R1',
      size: 214748364800,
      provisioningType: 'Thin',
      isShareable: false,
      provisioningParameters: {}  # TRY SETTING THIS
    },
    storage_system: '3par-01',
    storage_pool: 'SSD_r1',
    host_os_type: 'Windows Server 2016',
    attachment_data: {
      id: 1,
      lunType: 'Auto',
      storagePaths: [
        {
          isEnabled: true,
          targetSelector: 'Auto',
          connectionId: 1
        }
      ]
    }
  }
]
```

Also, from the details volume_attachments param you posted above, it looks like you're using the same name for 2 different volume attachments. The example in the tests shows 2 different ways to do volumes: one using the `:volume` key as a name, and the other using the `:volume_data` key with a storage_system, storage_pool, etc. For this debugging, please pick 1 or the other and start with just the 1 volume attachment.

If that still runs into issues, I'd suggest opening the file at the top of the stack trace and adding this to pause execution and look around:

```ruby
require 'pry'
binding.pry
```

When we get this figured out there will definitely need to be some documentation and/or code updates

**Comment by wingZero21** [comment]
Hi,

I tried adding that setting and it brought back the below. I tried adding the additional debug but it does not bring back much different than the original error.

Details:
```
400 BAD REQUEST {"errorCode":"UNRECOGNIZED_JSON_FIELD","message":"Unrecognized JSON field.","details":"The field named targetSelector near line 1, column 1,909 is not a valid field in this JSON object.","recommendedActions":["Check the valid fields for this JSON object and remove or correct the unrecognized field."],"errorSource":null,"nestedErrors":[],"data":{}}

```

Debug details:
```
stty: standard input: Inappropriate ioctl for device
[1] pry(#<Chef::Recipe>)> Converging 2 resources
Recipe: atchef_oneview_frame002_bay002_dc::default
  * oneview_server_profile_template[frame002_bay002_server_profile_template] action create
    
    ================================================================================
    Error executing action `create` on resource 'oneview_server_profile_template[frame002_bay002_server_profile_template]'
    ================================================================================

    OneviewSDK::BadRequest
    ----------------------
    400 BAD REQUEST {"errorCode":"UNRECOGNIZED_JSON_FIELD","message":"Unrecognized JSON field.","details":"The field named targetSelector near line 1, column 1,909 is not a valid field in this JSON object.","recommendedActions":["Check the valid fields for this JSON object and remove or correct the unrecognized field."],"errorSource":null,"nestedErrors":[],"data":{}}

    Cookbook Trace:
    ---------------
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/resource_provider.rb:106:in `block in create_or_update'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/resource_provider.rb:105:in `create_or_update'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/resource_providers/api200/server_profile_template_provider.rb:32:in `create_or_update'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/libraries/oneview_helper.rb:47:in `do_resource_action'
    /etc/chef/local-mode-cache/cache/cookbooks/oneview/resources/server_profile_template.rb:29:in `block in class_from_file'

volume_attachments [{:volume=>"TEST_R1", :attachment_data=>{:id=>1, :lunType=>"Auto", :storagePaths=>[{:isEnabled=>true, :targetSelector=>"Auto", :connectionId=>1}]}}, {:volume_data=>{:name=>"TEST_R1", :description=>"TEST_R1", :size=>214748364800, :provisioningType=>"Thin", :isShareable=>******, :provisioningParameters=>{}}, :storage_system=>"3par-01", :storage_pool=>"SSD_r1", :host_os_type=>"Windows Server 2016", :attachment_data=>{:id=>2, :lunType=>"Auto", :storagePaths=>[{:isEnabled=>true, :targetSelector=>"Auto", :connectionId=>1}]}}]

```

**Comment by jsmartt** [comment]
I keep seeing `:isShareable=>******` in your outputs. Are you setting that, and do you know if that is what is being sent, or is that just some sort of logging filtering?

I would recommend adding a pry statement in that `oneview/libraries/resource_provider.rb` file from the stacktrace to verify what `@item.data` looks like. Unfortunately it looks like Chef only logs the attributes before updating *existing* resources; otherwise you could just set the log mode to debug to see what it's sending.

You may also want to check that `@item.data.to_json` works, because I'm not sure why OneView is complaining that the JSON is not valid. [This](https://github.com/HewlettPackard/oneview-sdk-ruby/blob/master/lib/oneview-sdk/rest.rb#L281) is what converts the data to JSON, and it looks like it does try sending the data raw if it fails to convert it to JSON.

**Comment by wingZero21** [comment]
Hi,

@jsmartt I have tried removing the isShareable option and it still brings back the 400 bad request error.

That only seems to occur when I add in the ```provisioningParameters: {}```. 

When I remove that the error I seem to get back is the original below.

```
    NoMethodError
    -------------
    undefined method `each' for nil:NilClass
```

**Comment by jsmartt** [comment]
🤦‍♂️ I misread the 400 error message, which actually gives a bit more info than I thought. It's saying the `targetSelector` parameter is not a valid parameter. This parameter was renamed from `storageTargetType` to `targetSelector` in OneView 3.05 (API version 400). The default API version of this cookbook is 200 according to the docs & [attributes file](https://github.com/HewlettPackard/oneview-chef/blob/master/attributes/default.rb), so that's where I think we're getting that 400 error from. Try setting the `node['oneview']['api_version']` attribute to whatever your OneView version is (must be 400+) or using the old attribute: `storageTargetType`. Double-check the docs on your OneView appliance for valid examples and the complete list of parameters.

**Comment by soodpr** [comment]
@wingZero21 - let us know if setting the api_version attribute worked for you as mentioned by @jsmartt

**Comment by yuvirani** [comment]
This SDK has limited support and will not be actively developed for the foreseeable future.
