### ISSUE TITLE
OneviewCookbook::Helper#get_diff with two no-diff hashes returns '\n'

### ISSUE THREAD

**Issue by tmiotto** [HewlettPackard/oneview-chef#98]
### Scenario/Intent
When trying to compare two hashes that has no-diff ( i.e. for each key 'k' in 'a', a[k] == b[k] )  with the `OneviewCookbook::Helper#get_diff` the result returned is `'\n'`.

### Environment Details
 - **oneview Cookbook Version:** 1.1.0
 - **OneView Version:** N/A
 - **chef-client Version:** N/A
 - **platform:** N/A

### Steps to Reproduce
Use get_diff method with two hashes with no-diff like:
```ruby
a = { a: 'test', b: 'second' }
b = { a: 'test', c: 'other', b: 'second' }
get_diff(a, b)
```

### Expected Result
get_diff should return `''`

### Actual Result
get_diff returns `'\n'`

**Comment by jsmartt** [comment]
It uses `"\n"` as the initial string [here](https://github.com/HewlettPackard/oneview-chef/blob/7e0f5bd6ffc7fd1ef794c420f466c7fa72e5cf6e/libraries/oneview_helper.rb#L118), and I think I did that so that I could just tack the diff onto the end of the log statement ([like this](https://github.com/HewlettPackard/oneview-chef/blob/7e0f5bd6ffc7fd1ef794c420f466c7fa72e5cf6e/libraries/oneview_resource_base.rb#L48)), and not have to repeat myself. We can always just set the default string to an empty string and add a newline before the diff though (or set it to an empty string if recursive_diff returns just `\n`). That's fine with me :)
